-- Initial catalogue (the 10 launch products). Safe to re-run.
insert into public.products
  (slug, name, category, price, original_price, description, details, delivery, sizes,
   is_featured, is_bestseller, stock_quantity, image_url, sort_order)
values
  ('ambre-noir-eau-de-parfum', 'Labadi Coast Eau de Parfum', 'Perfumes', 1850, 2100, 'A smoked amber and coastal vetiver composition layered with dark resin and Ghanaian cedarwood. Understated, evocative, and exceptionally long-wearing.', '100ml. Extrait de Parfum, 22% concentration. Hand-blended in Grasse & Accra.', 'Same-day express delivery in Greater Accra (Cantonments, Osu, East Legon). 48-hour delivery across Ghana.', null, true, true, 18, '/images/product-ambre-noir-eau-de-parfum.jpg', 0),
  ('structured-leather-tote', 'Osu Leather Architecture Tote', 'Bags', 4600, null, 'Architectural full-grain calfskin crafted in a single clean silhouette. Suede-lined interior designed for urban ease and quiet authority.', 'Full-grain calfskin, solid brass hardware, brushed suede lining. Handcrafted in Florence & Accra.', 'Complimentary white-glove delivery in Greater Accra. Standard insured shipping nationwide.', null, true, false, 8, '/images/product-structured-leather-tote.jpg', 1),
  ('wool-wide-leg-trouser', 'Cantonments Tailored Linen Trouser', 'Clothing', 2200, null, 'Heavyweight breathable linen-wool blend with a fluid drape and a high tailored waistband. Designed for tropical elegance and effortless movement.', '70% organic linen, 30% virgin wool. Dry clean or delicate cool wash. Made in Portugal.', 'Express delivery within 24–48 hours across Ghana. Free exchanges.', array['XS', 'S', 'M', 'L', 'XL'], true, false, 14, '/images/product-wool-wide-leg-trouser.jpg', 2),
  ('silk-charmeuse-shirt', 'Kente-Weave Silk Charmeuse Shirt', 'Clothing', 2450, 2800, 'Liquid Mulberry silk featuring a subtle jacquard geometric weave inspired by heritage West African patterns. Drapes effortlessly for warm tropical evenings.', '100% Mulberry silk charmeuse. Concealed mother-of-pearl placket. Dry clean only.', 'Same-day dispatch in Accra. 48-hour delivery nationwide.', array['XS', 'S', 'M', 'L'], true, true, 11, '/images/product-silk-charmeuse-shirt.jpg', 3),
  ('cashmere-crewneck', 'Asante Light Cashmere Knit', 'Clothing', 2800, null, 'Ultra-fine 16-gauge Grade-A Mongolian cashmere with ribbed trims and a relaxed contemporary cut. Temperature-regulating for air-conditioned evenings.', '100% Grade-A Mongolian Cashmere. Hand wash cold or dry clean.', 'Express 24-hour delivery in Greater Accra.', array['S', 'M', 'L', 'XL'], true, false, 9, '/images/product-cashmere-crewneck.jpg', 4),
  ('minimal-gold-hoop', 'Ridge Gold Vermeil Hoop', 'Accessories', 1250, null, '18k gold vermeil over recycled sterling silver with a subtle sculpted ridge design. Lightweight hollow core designed for all-day comfort.', '18k Gold Vermeil (2.5 microns) over 925 Sterling Silver. Hinge closure.', 'Same-day express delivery in Greater Accra in signature box.', null, false, true, 22, '/images/product-minimal-gold-hoop.jpg', 5),
  ('vetiver-hand-balm', 'Akropong Botanical Hand Balm', 'Beauty', 420, null, 'Nourishing botanical hand cream enriched with raw unrefined shea butter, baobab oil, and wild Haitian vetiver. Restores moisture immediately.', '75ml aluminum tube. Organic West African Shea Butter & Cold-Pressed Baobab.', 'Express delivery across Greater Accra & Ghana nationwide.', null, true, false, 34, '/images/product-vetiver-hand-balm.jpg', 6),
  ('matte-silk-lip-oil', 'Prampram Sun Lip Oil', 'Beauty', 480, null, 'Non-sticky tinted botanical lip treatment with SPF 15 and jojoba seed oil. Leaves a subtle rosy sheen and continuous hydration.', '8ml glass vial with plush applicator. Organic jojoba, vitamin E, marula oil.', 'Same-day delivery in Accra.', null, false, true, 45, '/images/product-matte-silk-lip-oil.jpg', 7),
  ('quilted-crossbody', 'Nima Quilted Evening Crossbody', 'Bags', 3900, 4300, 'Butter-soft nappa leather in a geometric quilt pattern with a convertible gold curb chain strap. Fits phone, cards, key, and lip balm seamlessly.', 'Nappa leather, magnetic flap lock, gold-tone chain. Interior zip pocket.', 'Express 24-hour delivery across Greater Accra.', null, true, false, 6, '/images/product-quilted-crossbody.jpg', 8),
  ('tailored-wool-coat', 'Aburi Double-Faced Wool Coat', 'Clothing', 4950, null, 'Unstructured double-faced virgin wool coat with relaxed lapels and hand-stitched seams. Statement outerwear for international travel and crisp highland evenings.', '100% Virgin Wool. Unlined double-faced construction. Horn buttons.', 'Complimentary courier delivery across Ghana.', array['S', 'M', 'L'], true, false, 5, '/images/product-tailored-wool-coat.jpg', 9)
on conflict (slug) do nothing;
